### ISSUE TITLE
Styling issue on menu

### ISSUE THREAD

**Issue by JP1016** [PJijin/Show-Path#11]
**Describe the bug**
Styling issue on menu items
**To Reproduce**
Open the more menu on homepage

**Expected behavior**
It should be aligned
**Screenshots**
<img width="1680" alt="Screenshot 2019-09-17 at 10 00 47 PM" src="https://user-images.githubusercontent.com/5446313/65061059-b8c8cd00-d996-11e9-905f-818c899e65aa.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Latest

**Comment by PJijin** [comment]
🔮
