### ISSUE TITLE
Footer gets pulled up on menu

### ISSUE THREAD

**Issue by JP1016** [PJijin/Show-Path#12]
**Describe the bug**
clicking on menu is pulling the footer up the menu

**Expected behavior**
footer should not be pulled above

**Screenshots**
<img width="1679" alt="Screenshot 2019-09-18 at 10 20 57 PM" src="https://user-images.githubusercontent.com/5446313/65168766-d2cfe180-da62-11e9-9c96-03086039ea60.png">

**Comment by PJijin** [comment]
Fixed. 👍🏻

**Comment by JP1016** [comment]
footer still changes its position when clicking the menu
